Handle weird comment retrieval permissions case
Saw the error

Fetching journal entries for: palfrey
Fetching journal entry L-867 (create)
Fetching journal comments for: palfrey
*** Error fetching comment meta, possibly not community maintainer?

Traceback (most recent call last):
 File "ljdump.py", line 358, in <module>
   ljdump(server, username, password, username)
 File "ljdump.py", line 244, in ljdump
   r.close()
AttributeError: 'dict' object has no attribute 'close'

(notably, this is my personal journal, so missing permissions shouldn't
happen)

This patch handles this weird case (which will probably never now happen
again)